"""mysql initial schema dryrun

Revision ID: 832b942b94aa
Revises: 
Create Date: 2026-04-18 19:17:29.797495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '832b942b94aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('kakao_id', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_watchlist_public', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('role', sa.String(length=10), server_default=sa.text("'NORMAL'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('kakao_id')
    )
    op.create_table('analysis_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('article_published_at', sa.DateTime(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shared_card_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('author_nickname', sa.String(length=100), nullable=True),
    sa.Column('author_account_id', sa.Integer(), nullable=True),
    sa.Column('author_ip', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shared_card_id', sa.Integer(), nullable=False),
    sa.Column('liker_ip', sa.String(length=45), nullable=False),
    sa.Column('liker_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shared_card_id', 'liker_ip', name='uq_card_like_ip')
    )
    op.create_table('investment_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('link_hash', sa.String(length=64), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('published_at', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_news_link_hash'), 'investment_news', ['link_hash'], unique=True)
    op.create_table('investment_youtube_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_youtube_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('channel_name', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_youtube_videos_log_id'), 'investment_youtube_videos', ['log_id'], unique=False)
    op.create_index(op.f('ix_investment_youtube_videos_video_id'), 'investment_youtube_videos', ['video_id'], unique=False)
    op.create_table('market_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_videos_video_id'), 'market_videos', ['video_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_doc_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.String(length=50), nullable=False),
    sa.Column('collected_at', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=100), nullable=False),
    sa.Column('collector_version', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_doc_id', name='uq_dedup_key')
    )
    op.create_index(op.f('ix_raw_articles_symbol'), 'raw_articles', ['symbol'], unique=False)
    op.create_table('saved_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('link_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('published_at', sa.String(length=100), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'link_hash', name='uq_saved_articles_account_link')
    )
    op.create_table('shared_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('sharer_account_id', sa.Integer(), nullable=True),
    sa.Column('sharer_nickname', sa.String(length=100), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('themes', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('corp_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_stocks_name', 'stocks', ['name'], unique=False)
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interactions_account_id'), 'user_interactions', ['account_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('preferred_stocks', sa.Text(), nullable=False),
    sa.Column('interests_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('video_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.String(length=100), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.String(length=50), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_comments_comment_id'), 'video_comments', ['comment_id'], unique=True)
    op.create_index(op.f('ix_video_comments_video_id'), 'video_comments', ['video_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', name='uq_watchlist_account_symbol')
    )
    op.create_table('youtube_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=False),
    sa.Column('channel_name', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.String(length=50), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_videos_video_id'), 'youtube_videos', ['video_id'], unique=True)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('shared_card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_boards_shared_card', 'boards', ['shared_card_id'], unique=False)
    op.create_foreign_key('fk_boards_shared_card', 'boards', 'shared_cards', ['shared_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boards')
    op.drop_index(op.f('ix_youtube_videos_video_id'), table_name='youtube_videos')
    op.drop_table('youtube_videos')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_video_comments_video_id'), table_name='video_comments')
    op.drop_index(op.f('ix_video_comments_comment_id'), table_name='video_comments')
    op.drop_table('video_comments')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_interactions_account_id'), table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index('ix_stocks_name', table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('stock_themes')
    op.drop_table('shared_cards')
    op.drop_table('saved_articles')
    op.drop_index(op.f('ix_raw_articles_symbol'), table_name='raw_articles')
    op.drop_table('raw_articles')
    op.drop_table('posts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_market_videos_video_id'), table_name='market_videos')
    op.drop_table('market_videos')
    op.drop_index(op.f('ix_investment_youtube_videos_video_id'), table_name='investment_youtube_videos')
    op.drop_index(op.f('ix_investment_youtube_videos_log_id'), table_name='investment_youtube_videos')
    op.drop_table('investment_youtube_videos')
    op.drop_table('investment_youtube_logs')
    op.drop_index(op.f('ix_investment_news_link_hash'), table_name='investment_news')
    op.drop_table('investment_news')
    op.drop_table('card_likes')
    op.drop_table('card_comments')
    op.drop_table('analysis_logs')
    op.drop_table('accounts')
    # ### end Alembic commands ###
