"""add events table

Revision ID: a868115394d5
Revises: b7c9e2f4a831
Create Date: 2026-04-25 15:18:39.854619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a868115394d5'
down_revision: Union[str, None] = 'b7c9e2f4a831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('campaign', sa.String(length=50), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_account_id'), 'events', ['account_id'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_index(op.f('ix_analysis_logs_analyzed_at'), table_name='analysis_logs')
    op.drop_index(op.f('ix_analysis_logs_symbol'), table_name='analysis_logs')
    op.drop_index(op.f('ix_boards_created_at'), table_name='boards')
    op.drop_constraint(op.f('card_comments_ibfk_1'), 'card_comments', type_='foreignkey')
    op.drop_constraint(op.f('card_likes_ibfk_1'), 'card_likes', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_raw_articles_created_at'), table_name='raw_articles')
    op.drop_index(op.f('ix_saved_articles_saved_at'), table_name='saved_articles')
    op.drop_index(op.f('ix_shared_cards_created_at'), table_name='shared_cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shared_cards_created_at'), 'shared_cards', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_articles_saved_at'), 'saved_articles', ['saved_at'], unique=False)
    op.create_index(op.f('ix_raw_articles_created_at'), 'raw_articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_foreign_key(op.f('card_likes_ibfk_1'), 'card_likes', 'shared_cards', ['shared_card_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('card_comments_ibfk_1'), 'card_comments', 'shared_cards', ['shared_card_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_boards_created_at'), 'boards', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_logs_symbol'), 'analysis_logs', ['symbol'], unique=False)
    op.create_index(op.f('ix_analysis_logs_analyzed_at'), 'analysis_logs', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_account_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
