"""sync current schema

Revision ID: ef729a73e548
Revises: rkf23kknt8kl
Create Date: 2026-04-23 20:21:50.399459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'ef729a73e548'
down_revision: Union[str, None] = 'rkf23kknt8kl'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('accounts', sa.Column('role', sa.String(length=10), nullable=False))
    op.add_column('analysis_logs', sa.Column('article_published_at', sa.DateTime(), nullable=True))
    op.add_column('analysis_logs', sa.Column('source_name', sa.String(length=100), nullable=True))
    op.alter_column('analysis_logs', 'source_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_foreign_key(None, 'card_comments', 'shared_cards', ['shared_card_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'card_likes', 'shared_cards', ['shared_card_id'], ['id'], ondelete='CASCADE')
    op.alter_column('saved_articles', 'account_id',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_saved_articles_account_id'), 'saved_articles', ['account_id'], unique=False)
    op.add_column('user_interactions', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('user_interactions', sa.Column('market', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('investment_style', sa.String(length=20), nullable=False))
    op.add_column('user_profiles', sa.Column('risk_tolerance', sa.String(length=20), nullable=False))
    op.add_column('user_profiles', sa.Column('preferred_sectors', sa.Text(), nullable=False))
    op.add_column('user_profiles', sa.Column('analysis_preference', sa.String(length=20), nullable=False))
    op.add_column('user_profiles', sa.Column('keywords_of_interest', sa.Text(), nullable=False))
    op.alter_column('watchlist_items', 'symbol',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlist_items', 'symbol',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.drop_column('user_profiles', 'keywords_of_interest')
    op.drop_column('user_profiles', 'analysis_preference')
    op.drop_column('user_profiles', 'preferred_sectors')
    op.drop_column('user_profiles', 'risk_tolerance')
    op.drop_column('user_profiles', 'investment_style')
    op.drop_column('user_interactions', 'market')
    op.drop_column('user_interactions', 'name')
    op.drop_index(op.f('ix_saved_articles_account_id'), table_name='saved_articles')
    op.alter_column('saved_articles', 'account_id',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_constraint(None, 'card_likes', type_='foreignkey')
    op.drop_constraint(None, 'card_comments', type_='foreignkey')
    op.alter_column('analysis_logs', 'source_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.drop_column('analysis_logs', 'source_name')
    op.drop_column('analysis_logs', 'article_published_at')
    op.drop_column('accounts', 'role')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
